services:
  - type: web
    name: backend
    env: node
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
